#!/bin/bash
g++ publish.cpp -o publish -lpaho-mqtt3c
g++ subscribe.cpp -o subscribe -lpaho-mqtt3c
g++ GPIO.h window.cpp -o window -pthread -lpaho-mqtt3c
g++ GPIO.h app.cpp -o app -pthread -lpaho-mqtt3c
g++ textbox.cpp -o textbox -pthread -lpaho-mqtt3c
